#!/usr/bin/env bash
#
# The golden path. One command from "we need a service" to a repository that already has
# a health endpoint, metrics, probes, limits, a pipeline, alerts, and an owner.
#
# It is deliberately boring: envsubst over a directory of templates. A platform's value
# is in the DEFAULTS it encodes, not in the cleverness of its generator.
#
# Usage:  ./new-service.sh <service-name> <owner-team> [tier]
#
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

SERVICE_NAME="${1:-}"
OWNER="${2:-}"
TIER="${3:-2}"
PLATFORM_VERSION="$(cat PLATFORM-VERSION)"

usage() {
  cat >&2 <<EOF
usage: $0 <service-name> <owner-team> [tier]

  service-name   lowercase, hyphens only (becomes the k8s name and the image name)
  owner-team     the team that will be paged. NOT optional — see Break It scenario 3
  tier           1 = paged 24/7, 2 = business hours, 3 = best effort   (default: 2)
EOF
  exit 64
}

[[ -n "$SERVICE_NAME" && -n "$OWNER" ]] || usage
[[ "$SERVICE_NAME" =~ ^[a-z][a-z0-9-]{1,28}[a-z0-9]$ ]] || {
  echo "error: '$SERVICE_NAME' must be lowercase letters, digits and hyphens" >&2; exit 64; }
[[ "$TIER" =~ ^[123]$ ]] || { echo "error: tier must be 1, 2 or 3" >&2; exit 64; }

OUT="services/$SERVICE_NAME"
[[ -e "$OUT" ]] && { echo "error: $OUT already exists" >&2; exit 1; }

export SERVICE_NAME OWNER TIER PLATFORM_VERSION

mkdir -p "$OUT"/{app,k8s,.github/workflows,monitoring}

render() { envsubst '$SERVICE_NAME $OWNER $TIER $PLATFORM_VERSION' <"templates/$1" >"$OUT/$2"; }

render service.yaml.tmpl      service.yaml            # the catalogue entry: who owns this
render Dockerfile.tmpl        app/Dockerfile
render app.py.tmpl            app/app.py
render requirements.txt.tmpl  app/requirements.txt
render deployment.yml.tmpl    k8s/deployment.yml      # probes + limits + non-root, by default
render ci.yml.tmpl            .github/workflows/ci.yml
render alerts.yml.tmpl        monitoring/alerts.yml   # the four golden signals, pre-wired

cat >"$OUT/README.md" <<EOF
# $SERVICE_NAME

Generated by the platform golden path, template version \`$PLATFORM_VERSION\`.
Owner: **$OWNER** · Tier **$TIER**

## What you already have

- \`/healthz\` (liveness) and \`/readyz\` (readiness — checks dependencies)
- \`/metrics\` with request count, error count, and latency histogram
- A Deployment with both probes, resource requests and limits, and a non-root securityContext
- A pipeline that lints, tests, builds a SHA-tagged image, and scans it
- Four alerts on the golden signals, and a catalogue entry that says who to page

## The escape hatch

Every file here is a real file, not a hidden abstraction. Edit anything. If you had to
change something the template got wrong, **tell the platform team** — that is how the
template improves. Bypassing the path silently is the only failure mode that matters.

## Next

    ./platform-check.sh services/$SERVICE_NAME    # the policy gate CI will run
EOF

printf '\n✅ %s created at %s (template %s)\n' "$SERVICE_NAME" "$OUT" "$PLATFORM_VERSION"
printf '   owner: %s · tier: %s\n\n' "$OWNER" "$TIER"
printf '   next:  ./platform-check.sh %s\n\n' "services/$SERVICE_NAME"
